server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://175.24.120.38:3306/JlgTest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Woshibenzhu20131
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml